:PROPERTIES:
:ID:       56df45dd-17f8-4106-8f19-66f1b5dc8b36
:END:

#+TITLE: DragEvac
#+DATE: 2026-04-26

Load files and text, and drop them faster than Terran players dropping widow mines into your mineral line

* What Does DragEvac Do?
DragEvac creates a window on your screen where you can drag and drop text and files into it. Once loaded, you can also drag them back out into other programs, as if you dragged them out from the original program. Now you don't get into those situation where you are in the middle of dragging an item into your browser, and you need to click on a link, but you are already holding onto a file.

In some modes of DragEvac, the items you dropped into it are saved so that you can re-launch this program, and drop them back in immediately!

** Program Modes
- =no-save=: Always start from an empty list. When the program exits, nothing is saved.
- =temporary=: The items in the list is saved for the current boot. When the computer restarts, the list is automatically emptied.
- =persistent=: The items in the list is always saved. Nothing changes when you close the program and come back to it later.
- =read-only=: User specifies the items that should appear in the list. You cannot drag and drop items into the list.

** Basic Keybinds
- Escape: Immediately quits the program.

* Full =--help= Output
#+begin_src
  Quickly drag and drop across multiple windows without having to hold your left mouse button down!
  
  Usage: dragevac [OPTIONS] [COMMAND]
  
  Commands:
    config      Writes default config. If config already exists, this will fill out missing fields, delete invalid fields, and write the result back
    no-save     Default execution method. The entry list is completely empty, and can be filled by dropping items into it. The list is not saved when the program exits
    temporary   The entry list is saved into a specific directory in /tmp. The entry list state file is updated whenever user adds or removes entries from them. This allows user to have a persistent list that automatically resets when the computer reboots
    persistent  Stores the entries in a specified location for complete permanence
    read-only   User cannot drag items into the list. User must specify the state file and/or a preload directory from which the list of entries will be pre-filled
    help        Print this message or the help of the given subcommand(s)
  
  Options:
    -v, --verbose              Enable verbose output
        --load <LOAD>          Loads items from a file on startup
        --load-dir <LOAD_DIR>  Loads all items from a directory as entries on startup
    -c, --config <CONFIG>      Path to config file
    -h, --help                 Print help  
#+end_src

* Building
#+begin_src rust
  cargo build --release  
#+end_src

If you have Nix, you can also do the following:
#+begin_src shell
  nix build
#+end_src
